# Generated by Django 4.1 on 2023-08-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_github_project_tagline_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='media/header_images/'),
        ),
    ]
