# Generated by Django 4.1 on 2023-08-27 01:26

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='header_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['top', 'left'], force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1024, 300], upload_to='media/images/'),
        ),
    ]
